### ISSUE TITLE
Don't use bullet points

### ISSUE THREAD

**Issue by tomasz-buchta** [SoftwareEngineeringProjectCEIE/2.-Analysis-and-Project-Requirements-APR-#1]
@jonaszmclaren 
As tutor described on exercises - it's hard to make a reference to exact point of document when using bullet point. Referencing to something like 3rd bullet point in 4th dash leads to confusion. Instead you could use sub ordered lists, like:
1. Section 1
1.1. Subsection 1 of section 1

**Comment by jonaszmclaren** [comment]
Fixed
