### ISSUE TITLE
Current state of code

### ISSUE THREAD

**Issue by tomasz-buchta** [SoftwareEngineeringProjectCEIE/2.-Analysis-and-Project-Requirements-APR-#3]
@jonaszmclaren 
By now we can say that the project compiles(yay!) and works without any clearly noticeable bugs. During the development we should do some refactoring of existing code to avoid things like:
```
if (!"".Equals(path)){...}
```

**Comment by gabr** [comment]
There are also hard codded variables such:

```cs
file_dir = "c:\\SE_test";
batch_dir = "c:\\SE_test\\test_batch.bat";
```
